<a href="https://colab.research.google.com/github/Farhana-Tani/PyTorch-basics/blob/main/Create_Linear_Regression_Model_with_Pytorch_Components.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Data gathering
# 2. Data preprocessing
# 3. Feature engineering
# 4. Model training
# 5. Testing

In [ ]:
## Dataset used
# https://www.kaggle.com/datasets/mirichoi0218/insurance

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

print(f"Path of dataset files : {path}")

Using Colab cache for faster access to the 'insurance' dataset.
Path of dataset files : /kaggle/input/insurance

In [ ]:
import os
print(os.getcwd())

/content

In [ ]:
import pandas as pd

In [ ]:
os.listdir('/kaggle/input/insurance')

['insurance.csv']

In [ ]:
df = pd.read_csv(os.path.join(path,'insurance.csv'))

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
# Split dataset before Encoding
train_df,test_df= train_test_split(df,test_size=0.2,random_state=42)

In [ ]:
# Encode categorical variable
label_encoder={}
for col in ['sex','smoker','region']:
    le=LabelEncoder()
    label_encoder[col]=LabelEncoder()
    train_df[col]=le.fit_transform(train_df[col])
    test_df[col]=le.transform(test_df[col])
    label_encoder[col]=le

In [ ]:
# Features and target
X_train=train_df.drop(columns=['charges'])
y_train=train_df['charges']
X_test=test_df.drop(columns=['charges'])
y_test=test_df['charges']

In [ ]:
print(X_train)

      age  sex     bmi  children  smoker  region
560    46    0  19.950         2       0       1
1285   47    0  24.320         0       0       0
1142   52    0  24.860         0       0       2
969    39    0  34.320         5       0       2
486    54    0  21.470         3       0       1
...   ...  ...     ...       ...     ...     ...
1095   18    0  31.350         4       0       0
1130   39    0  23.870         5       0       2
1294   58    1  25.175         0       0       0
860    37    0  47.600         2       1       3
1126   55    1  29.900         0       0       3

[1070 rows x 6 columns]

In [ ]:
print(X_train.head())

      age  sex    bmi  children  smoker  region
560    46    0  19.95         2       0       1
1285   47    0  24.32         0       0       0
1142   52    0  24.86         0       0       2
969    39    0  34.32         5       0       2
486    54    0  21.47         3       0       1

In [ ]:
print(X_train.head())
print(y_train.head())

      age  sex    bmi  children  smoker  region
560    46    0  19.95         2       0       1
1285   47    0  24.32         0       0       0
1142   52    0  24.86         0       0       2
969    39    0  34.32         5       0       2
486    54    0  21.47         3       0       1
560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
Name: charges, dtype: float64

In [ ]:
# Normalize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print(X_train)

[[ 0.47222651 -1.0246016  -1.75652513  0.73433626 -0.50874702 -0.45611589]
 [ 0.54331294 -1.0246016  -1.03308239 -0.91119211 -0.50874702 -1.35325561]
 [ 0.8987451  -1.0246016  -0.94368672 -0.91119211 -0.50874702  0.44102382]
 ...
 [ 1.3252637   0.97598911 -0.89153925 -0.91119211 -0.50874702 -1.35325561]
 [-0.16755139 -1.0246016   2.82086429  0.73433626  1.96561348  1.33816354]
 [ 1.1120044   0.97598911 -0.10932713 -0.91119211 -0.50874702  1.33816354]]

In [ ]:
# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor= torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor= torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [ ]:
print(y_train_tensor)

tensor([[ 9193.8389],
        [ 8534.6719],
        [27117.9941],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])

In [ ]:
print(y_train_tensor)
print(y_train_tensor.shape)

tensor([[ 9193.8389],
        [ 8534.6719],
        [27117.9941],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])
torch.Size([1070, 1])

In [ ]:
print(X_test_tensor)
print(X_test_tensor.shape)

tensor([[ 0.4011, -1.0246, -0.8915,  0.7343, -0.5087, -1.3533],
        [-0.2386, -1.0246, -0.0895, -0.9112, -0.5087, -0.4561],
        [ 1.7518, -1.0246, -0.6085, -0.9112,  1.9656, -0.4561],
        ...,
        [-0.0965,  0.9760, -0.4197, -0.0884, -0.5087, -1.3533],
        [ 1.0409, -1.0246,  2.7894, -0.9112,  1.9656,  0.4410],
        [ 0.8277, -1.0246,  0.6025, -0.0884, -0.5087,  1.3382]])
torch.Size([268, 6])

In [ ]:
# Define Neural network model

class SimpleNNRegressionModel(nn.Module):
  def __init__(self, input_dim):
    super(SimpleNNRegressionModel, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(input_dim, 64),
        nn.ReLU(),
        nn.Linear(64, 128),
        nn.ReLU(),
        nn.Linear(128, 1)
    )

  def forward(self, x):
    return self.network(x)

In [ ]:
X_train_tensor.shape

torch.Size([1070, 6])

In [ ]:
input_dim = X_train_tensor.shape[1]
model = SimpleNNRegressionModel(input_dim)

In [ ]:
print(model)

SimpleNNRegressionModel(
  (network): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)

In [ ]:
# Loss and optmiser

criterion = nn.MSELoss()
optimiser = optim.Adam(model.parameters(), lr=0.01)

In [ ]:
# Training loop
epochs = 30000

for epoch in range(epochs):
  model.train()
  optimiser.zero_grad()
  predictions = model(X_train_tensor)
  loss = criterion(predictions, y_train_tensor)
  loss.backward()

  optimiser.step()

  if (epoch+1) % 100 == 0:
    print(f"Epoch [{epoch+1}/{epochs}], Loss : {loss.item():.4f}")

Epoch [100/30000], Loss : 50803320.0000
Epoch [200/30000], Loss : 32098724.0000
Epoch [300/30000], Loss : 29610258.0000
Epoch [400/30000], Loss : 27478008.0000
Epoch [500/30000], Loss : 26304884.0000
Epoch [600/30000], Loss : 25645000.0000
Epoch [700/30000], Loss : 25145586.0000
Epoch [800/30000], Loss : 24755742.0000
Epoch [900/30000], Loss : 24429966.0000
Epoch [1000/30000], Loss : 24185194.0000
Epoch [1100/30000], Loss : 23969972.0000
Epoch [1200/30000], Loss : 23810744.0000
Epoch [1300/30000], Loss : 23675284.0000
Epoch [1400/30000], Loss : 23519526.0000
Epoch [1500/30000], Loss : 23379016.0000
Epoch [1600/30000], Loss : 23254790.0000
Epoch [1700/30000], Loss : 23144768.0000
Epoch [1800/30000], Loss : 23052260.0000
Epoch [1900/30000], Loss : 22974892.0000
Epoch [2000/30000], Loss : 22894124.0000
Epoch [2100/30000], Loss : 22823314.0000
Epoch [2200/30000], Loss : 22764048.0000
Epoch [2300/30000], Loss : 22694900.0000
Epoch [2400/30000], Loss : 22513436.0000
Epoch [2500/30000], Loss : 22306000.0000
Epoch [2600/30000], Loss : 22156900.0000
Epoch [2700/30000], Loss : 21998346.0000
Epoch [2800/30000], Loss : 21787476.0000
Epoch [2900/30000], Loss : 21436998.0000
Epoch [3000/30000], Loss : 20862772.0000
Epoch [3100/30000], Loss : 20135098.0000
Epoch [3200/30000], Loss : 19436266.0000
Epoch [3300/30000], Loss : 18841576.0000
Epoch [3400/30000], Loss : 18315950.0000
Epoch [3500/30000], Loss : 17841120.0000
Epoch [3600/30000], Loss : 17409018.0000
Epoch [3700/30000], Loss : 16955682.0000
Epoch [3800/30000], Loss : 16584189.0000
Epoch [3900/30000], Loss : 16274133.0000
Epoch [4000/30000], Loss : 15958026.0000
Epoch [4100/30000], Loss : 15659850.0000
Epoch [4200/30000], Loss : 15389053.0000
Epoch [4300/30000], Loss : 15107272.0000
Epoch [4400/30000], Loss : 14760279.0000
Epoch [4500/30000], Loss : 14400837.0000
Epoch [4600/30000], Loss : 14021764.0000
Epoch [4700/30000], Loss : 13575928.0000
Epoch [4800/30000], Loss : 13193818.0000
Epoch [4900/30000], Loss : 12838445.0000
Epoch [5000/30000], Loss : 12569920.0000
Epoch [5100/30000], Loss : 12313720.0000
Epoch [5200/30000], Loss : 12095268.0000
Epoch [5300/30000], Loss : 11914912.0000
Epoch [5400/30000], Loss : 11722967.0000
Epoch [5500/30000], Loss : 11552385.0000
Epoch [5600/30000], Loss : 11418564.0000
Epoch [5700/30000], Loss : 11293136.0000
Epoch [5800/30000], Loss : 11161173.0000
Epoch [5900/30000], Loss : 10941830.0000
Epoch [6000/30000], Loss : 10786739.0000
Epoch [6100/30000], Loss : 10669359.0000
Epoch [6200/30000], Loss : 10547800.0000
Epoch [6300/30000], Loss : 10426590.0000
Epoch [6400/30000], Loss : 10323573.0000
Epoch [6500/30000], Loss : 10235614.0000
Epoch [6600/30000], Loss : 10141095.0000
Epoch [6700/30000], Loss : 10023054.0000
Epoch [6800/30000], Loss : 9930234.0000
Epoch [6900/30000], Loss : 9845429.0000
Epoch [7000/30000], Loss : 9758463.0000
Epoch [7100/30000], Loss : 9665358.0000
Epoch [7200/30000], Loss : 9591154.0000
Epoch [7300/30000], Loss : 9530184.0000
Epoch [7400/30000], Loss : 9462771.0000
Epoch [7500/30000], Loss : 9347066.0000
Epoch [7600/30000], Loss : 9271203.0000
Epoch [7700/30000], Loss : 9181257.0000
Epoch [7800/30000], Loss : 9028426.0000
Epoch [7900/30000], Loss : 8929414.0000
Epoch [8000/30000], Loss : 8838252.0000
Epoch [8100/30000], Loss : 8725127.0000
Epoch [8200/30000], Loss : 8626077.0000
Epoch [8300/30000], Loss : 8539551.0000
Epoch [8400/30000], Loss : 8444428.0000
Epoch [8500/30000], Loss : 8353917.5000
Epoch [8600/30000], Loss : 8281789.5000
Epoch [8700/30000], Loss : 8217845.0000
Epoch [8800/30000], Loss : 8152288.0000
Epoch [8900/30000], Loss : 8103151.5000
Epoch [9000/30000], Loss : 8041467.0000
Epoch [9100/30000], Loss : 7990599.0000
Epoch [9200/30000], Loss : 7949259.5000
Epoch [9300/30000], Loss : 7891635.0000
Epoch [9400/30000], Loss : 7840898.0000
Epoch [9500/30000], Loss : 7789019.0000
Epoch [9600/30000], Loss : 7737712.5000
Epoch [9700/30000], Loss : 7700114.0000
Epoch [9800/30000], Loss : 7650284.5000
Epoch [9900/30000], Loss : 7601883.5000
Epoch [10000/30000], Loss : 7555575.5000
Epoch [10100/30000], Loss : 7515406.5000
Epoch [10200/30000], Loss : 7466255.0000
Epoch [10300/30000], Loss : 7406771.0000
Epoch [10400/30000], Loss : 7353617.0000
Epoch [10500/30000], Loss : 7309387.0000
Epoch [10600/30000], Loss : 7260844.0000
Epoch [10700/30000], Loss : 7224210.5000
Epoch [10800/30000], Loss : 7165781.0000
Epoch [10900/30000], Loss : 7133073.0000
Epoch [11000/30000], Loss : 7083073.0000
Epoch [11100/30000], Loss : 7053649.0000
Epoch [11200/30000], Loss : 7005197.5000
Epoch [11300/30000], Loss : 6972599.0000
Epoch [11400/30000], Loss : 6932131.0000
Epoch [11500/30000], Loss : 6884807.5000
Epoch [11600/30000], Loss : 6862835.0000
Epoch [11700/30000], Loss : 6812338.0000
Epoch [11800/30000], Loss : 6773401.5000
Epoch [11900/30000], Loss : 6754843.5000
Epoch [12000/30000], Loss : 6705450.0000
Epoch [12100/30000], Loss : 6672796.5000
Epoch [12200/30000], Loss : 6641486.5000
Epoch [12300/30000], Loss : 6606464.0000
Epoch [12400/30000], Loss : 6575768.0000
Epoch [12500/30000], Loss : 6542417.5000
Epoch [12600/30000], Loss : 6518429.0000
Epoch [12700/30000], Loss : 6490780.0000
Epoch [12800/30000], Loss : 6451883.5000
Epoch [12900/30000], Loss : 6428473.0000
Epoch [13000/30000], Loss : 6416861.5000
Epoch [13100/30000], Loss : 6382455.5000
Epoch [13200/30000], Loss : 6354644.5000
Epoch [13300/30000], Loss : 6317049.5000
Epoch [13400/30000], Loss : 6284155.5000
Epoch [13500/30000], Loss : 6254509.0000
Epoch [13600/30000], Loss : 6228563.5000
Epoch [13700/30000], Loss : 6210031.5000
Epoch [13800/30000], Loss : 6188418.5000
Epoch [13900/30000], Loss : 6160044.5000
Epoch [14000/30000], Loss : 6138285.5000
Epoch [14100/30000], Loss : 6115736.0000
Epoch [14200/30000], Loss : 6088465.5000
Epoch [14300/30000], Loss : 6059688.5000
Epoch [14400/30000], Loss : 6037219.0000
Epoch [14500/30000], Loss : 6011800.5000
Epoch [14600/30000], Loss : 5976143.5000
Epoch [14700/30000], Loss : 5963323.5000
Epoch [14800/30000], Loss : 5927271.0000
Epoch [14900/30000], Loss : 5897998.5000
Epoch [15000/30000], Loss : 5881544.5000
Epoch [15100/30000], Loss : 5845893.5000
Epoch [15200/30000], Loss : 5822469.0000
Epoch [15300/30000], Loss : 5799170.0000
Epoch [15400/30000], Loss : 5777374.0000
Epoch [15500/30000], Loss : 5766115.0000
Epoch [15600/30000], Loss : 5732101.5000
Epoch [15700/30000], Loss : 5705948.0000
Epoch [15800/30000], Loss : 5680156.5000
Epoch [15900/30000], Loss : 5666504.0000
Epoch [16000/30000], Loss : 5648517.5000
Epoch [16100/30000], Loss : 5613635.5000
Epoch [16200/30000], Loss : 5605846.5000
Epoch [16300/30000], Loss : 5575721.5000
Epoch [16400/30000], Loss : 5531796.0000
Epoch [16500/30000], Loss : 5516342.5000
Epoch [16600/30000], Loss : 5481017.5000
Epoch [16700/30000], Loss : 5466124.5000
Epoch [16800/30000], Loss : 5444263.5000
Epoch [16900/30000], Loss : 5410055.5000
Epoch [17000/30000], Loss : 5371872.5000
Epoch [17100/30000], Loss : 5340873.5000
Epoch [17200/30000], Loss : 5329351.0000
Epoch [17300/30000], Loss : 5280709.5000
Epoch [17400/30000], Loss : 5241728.0000
Epoch [17500/30000], Loss : 5228363.5000
Epoch [17600/30000], Loss : 5195419.0000
Epoch [17700/30000], Loss : 5153358.5000
Epoch [17800/30000], Loss : 5134819.0000
Epoch [17900/30000], Loss : 5102842.0000
Epoch [18000/30000], Loss : 5060124.0000
Epoch [18100/30000], Loss : 5036791.5000
Epoch [18200/30000], Loss : 5005167.0000
Epoch [18300/30000], Loss : 4984888.5000
Epoch [18400/30000], Loss : 4976808.5000
Epoch [18500/30000], Loss : 4930810.5000
Epoch [18600/30000], Loss : 4904216.0000
Epoch [18700/30000], Loss : 4889195.0000
Epoch [18800/30000], Loss : 4853270.5000
Epoch [18900/30000], Loss : 4825108.0000
Epoch [19000/30000], Loss : 4818510.5000
Epoch [19100/30000], Loss : 4801077.0000
Epoch [19200/30000], Loss : 4764284.5000
Epoch [19300/30000], Loss : 4744843.5000
Epoch [19400/30000], Loss : 4722323.5000
Epoch [19500/30000], Loss : 4692436.5000
Epoch [19600/30000], Loss : 4685295.0000
Epoch [19700/30000], Loss : 4672122.0000
Epoch [19800/30000], Loss : 4633498.5000
Epoch [19900/30000], Loss : 4613164.5000
Epoch [20000/30000], Loss : 4593929.5000
Epoch [20100/30000], Loss : 4573582.5000
Epoch [20200/30000], Loss : 4552003.5000
Epoch [20300/30000], Loss : 4536144.5000
Epoch [20400/30000], Loss : 4517410.0000
Epoch [20500/30000], Loss : 4507697.0000
Epoch [20600/30000], Loss : 4494142.5000
Epoch [20700/30000], Loss : 4484005.0000
Epoch [20800/30000], Loss : 4445394.5000
Epoch [20900/30000], Loss : 4427917.0000
Epoch [21000/30000], Loss : 4417058.0000
Epoch [21100/30000], Loss : 4404758.0000
Epoch [21200/30000], Loss : 4378384.5000
Epoch [21300/30000], Loss : 4368386.5000
Epoch [21400/30000], Loss : 4346518.5000
Epoch [21500/30000], Loss : 4329648.0000
Epoch [21600/30000], Loss : 4319929.5000
Epoch [21700/30000], Loss : 4317883.5000
Epoch [21800/30000], Loss : 4295739.5000
Epoch [21900/30000], Loss : 4277635.5000
Epoch [22000/30000], Loss : 4253730.0000
Epoch [22100/30000], Loss : 4276067.0000
Epoch [22200/30000], Loss : 4234471.5000
Epoch [22300/30000], Loss : 4208357.5000
Epoch [22400/30000], Loss : 4193313.0000
Epoch [22500/30000], Loss : 4181744.7500
Epoch [22600/30000], Loss : 4149086.2500
Epoch [22700/30000], Loss : 4148410.2500
Epoch [22800/30000], Loss : 4138994.0000
Epoch [22900/30000], Loss : 4110421.2500
Epoch [23000/30000], Loss : 4094247.7500
Epoch [23100/30000], Loss : 4092163.7500
Epoch [23200/30000], Loss : 4075966.5000
Epoch [23300/30000], Loss : 4085848.5000
Epoch [23400/30000], Loss : 4042527.0000
Epoch [23500/30000], Loss : 4030700.5000
Epoch [23600/30000], Loss : 4027813.5000
Epoch [23700/30000], Loss : 4034140.2500
Epoch [23800/30000], Loss : 3994744.7500
Epoch [23900/30000], Loss : 3975751.2500
Epoch [24000/30000], Loss : 3966324.7500
Epoch [24100/30000], Loss : 3963710.2500
Epoch [24200/30000], Loss : 3925799.5000
Epoch [24300/30000], Loss : 3912508.7500
Epoch [24400/30000], Loss : 3926197.2500
Epoch [24500/30000], Loss : 3887420.0000
Epoch [24600/30000], Loss : 3878180.7500
Epoch [24700/30000], Loss : 3852481.0000
Epoch [24800/30000], Loss : 3849538.2500
Epoch [24900/30000], Loss : 3841916.7500
Epoch [25000/30000], Loss : 3820557.2500
Epoch [25100/30000], Loss : 3838977.7500
Epoch [25200/30000], Loss : 3805979.7500
Epoch [25300/30000], Loss : 3779083.5000
Epoch [25400/30000], Loss : 3765401.2500
Epoch [25500/30000], Loss : 3761491.2500
Epoch [25600/30000], Loss : 3747475.0000
Epoch [25700/30000], Loss : 3728396.0000
Epoch [25800/30000], Loss : 3737221.5000
Epoch [25900/30000], Loss : 3725708.5000
Epoch [26000/30000], Loss : 3709420.5000
Epoch [26100/30000], Loss : 3707311.5000
Epoch [26200/30000], Loss : 3694227.0000
Epoch [26300/30000], Loss : 3706675.5000
Epoch [26400/30000], Loss : 3658626.5000
Epoch [26500/30000], Loss : 3653927.5000
Epoch [26600/30000], Loss : 3661595.0000
Epoch [26700/30000], Loss : 3628071.2500
Epoch [26800/30000], Loss : 3646828.5000
Epoch [26900/30000], Loss : 3606385.7500
Epoch [27000/30000], Loss : 3600297.5000
Epoch [27100/30000], Loss : 3587141.5000
Epoch [27200/30000], Loss : 3579941.7500
Epoch [27300/30000], Loss : 3584887.7500
Epoch [27400/30000], Loss : 3566548.2500
Epoch [27500/30000], Loss : 3561357.0000
Epoch [27600/30000], Loss : 3599690.2500
Epoch [27700/30000], Loss : 3592337.7500
Epoch [27800/30000], Loss : 3574124.5000
Epoch [27900/30000], Loss : 3530906.0000
Epoch [28000/30000], Loss : 3538810.5000
Epoch [28100/30000], Loss : 3501854.2500
Epoch [28200/30000], Loss : 3514168.0000
Epoch [28300/30000], Loss : 3484147.7500
Epoch [28400/30000], Loss : 3519154.7500
Epoch [28500/30000], Loss : 3486605.7500
Epoch [28600/30000], Loss : 3459783.7500
Epoch [28700/30000], Loss : 3492095.5000
Epoch [28800/30000], Loss : 3444584.5000
Epoch [28900/30000], Loss : 3437863.2500
Epoch [29000/30000], Loss : 3458849.5000
Epoch [29100/30000], Loss : 3444701.0000
Epoch [29200/30000], Loss : 3456435.0000
Epoch [29300/30000], Loss : 3436285.0000
Epoch [29400/30000], Loss : 3410441.2500
Epoch [29500/30000], Loss : 3403820.7500
Epoch [29600/30000], Loss : 3419582.0000
Epoch [29700/30000], Loss : 3383595.0000
Epoch [29800/30000], Loss : 3394930.0000
Epoch [29900/30000], Loss : 3381323.2500
Epoch [30000/30000], Loss : 3360263.7500

In [ ]:
# Model Evaluation

model.eval()
y_pred = model(X_test_tensor).detach().numpy()

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

y_test_numpy = y_test_tensor.numpy()

# Calculate metrics
mse = mean_squared_error(y_test_numpy, y_pred)
rmse = mse ** 0.5
mae = mean_absolute_error(y_test_numpy, y_pred)
r2 = r2_score(y_test_numpy, y_pred)

print(f"MSE : {mse}")
print(f"RMSE : {rmse}")
print(f"MAE : {mae}")
print(f"R2-Score : {r2}")

# 0 --> 0

MSE : 51058384.0
RMSE : 7145.514956950268
MAE : 4756.08935546875
R2-Score : 0.6711188554763794

In [ ]:
def predict_charges(age, sex, bmi, children, smoker,region):
  input_data = pd.DataFrame([[age, sex, bmi, children, smoker,region]],
               columns=['age', 'sex', 'bmi', 'children', 'smoker', 'region'])

  for col in ['sex', 'smoker', 'region']:
    input_data[col] = label_encoder[col].transform(input_data[col])
  input_data = scaler.transform(input_data)
  input_tensor = torch.tensor(input_data, dtype=torch.float32)
  predicted_charge = model(input_tensor).item()
  return predicted_charge

In [ ]:
predicted = predict_charges(50, 'female', 27.9, 0, 'yes', 'southwest')

In [ ]:
print(f"Predicted insurance charge: ${predicted:.2f}")

Predicted insurance charge: $16767.90

## Understanding components of a Custom DataLoader in PyTorch

1. Dataset(torch.utils.data.Dataset)
2. DataLoader(torch.utils.data.dataLoader)

In [ ]:
# Creating our custom Dataset in pytorch
# init() - initialised the dataset, loads data, applied preprocessing
# len() - return the total numbers of samples in the dataset
# getitem() - Defines how to retrieve a single data sample when an index is provide

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
class InsuranceDataset(Dataset):
  def __init__(self,X,y):
    self.X=X
    self.y=y
  def __len__(self):
    return len(self.X)
  def __getitem__(self,idx):
    features=torch.tensor(self.X[idx],dtype=torch.float32)
    target= torch.tensor(self.y.values[idx],dtype=torch.float32)
    return features,target

In [ ]:
dataset= InsuranceDataset(X_train,y_train)

In [ ]:
dataloader= DataLoader(dataset,batch_size=32,shuffle=True)

In [ ]:
for batch_idx,(features,targets) in enumerate(dataloader):
  print(f"Batch {batch_idx+1} :")
  print("Features:",features.shape)
  print("Targets:",targets.shape)
  break

Batch 1 :
Features: torch.Size([32, 6])
Targets: torch.Size([32])

In [ ]:
1070/32

33.4375

In [ ]:
epochs=1000
for epoch in range(epochs):
  model.train()
  for batch_idx,(batch_X,batch_y) in enumerate(dataloader):
    print(f"Current batch : {batch_idx}")
    optimiser.zero_grad()
    predictions=model(batch_X)
    loss=criterion(predictions,batch_y)
    loss.backward()
    optimiser.step()
    print(f'Batch [{batch_idx+1}/{epochs}], Loss: {loss.item():4f}')

  if (epochs+1) % 100 == 0:
    print(f"Epoch [{epoch+1}/{epochs}], Loss : {loss.item():.4f}")

Current batch : 0
Batch [1/1000], Loss: 298163520.000000
Current batch : 1
Batch [2/1000], Loss: 133473904.000000
Current batch : 2
Batch [3/1000], Loss: 134393136.000000
Current batch : 3
Batch [4/1000], Loss: 351834688.000000
Current batch : 4
Batch [5/1000], Loss: 252247456.000000
Current batch : 5
Batch [6/1000], Loss: 187159264.000000
Current batch : 6
Batch [7/1000], Loss: 199475584.000000
Current batch : 7
Batch [8/1000], Loss: 225182208.000000
Current batch : 8
Batch [9/1000], Loss: 346958848.000000
Current batch : 9
Batch [10/1000], Loss: 298656384.000000
Current batch : 10
Batch [11/1000], Loss: 186196656.000000
Current batch : 11
Batch [12/1000], Loss: 229405616.000000
Current batch : 12
Batch [13/1000], Loss: 216063328.000000
Current batch : 13
Batch [14/1000], Loss: 181187040.000000
Current batch : 14
Batch [15/1000], Loss: 191747696.000000
Current batch : 15
Batch [16/1000], Loss: 200059520.000000
Current batch : 16
Batch [17/1000], Loss: 154092816.000000
Current batch : 17
Batch [18/1000], Loss: 231555072.000000
Current batch : 18
Batch [19/1000], Loss: 138866256.000000
Current batch : 19
Batch [20/1000], Loss: 224639008.000000
Current batch : 20
Batch [21/1000], Loss: 228677632.000000
Current batch : 21
Batch [22/1000], Loss: 166807040.000000
Current batch : 22
Batch [23/1000], Loss: 134715616.000000
Current batch : 23
Batch [24/1000], Loss: 180575360.000000
Current batch : 24
Batch [25/1000], Loss: 287539808.000000
Current batch : 25
Batch [26/1000], Loss: 173100768.000000
Current batch : 26
Batch [27/1000], Loss: 164399856.000000
Current batch : 27
Batch [28/1000], Loss: 150924448.000000
Current batch : 28
Batch [29/1000], Loss: 168119280.000000
Current batch : 29
Batch [30/1000], Loss: 142013696.000000
Current batch : 30
Batch [31/1000], Loss: 147999552.000000
Current batch : 31
Batch [32/1000], Loss: 275030880.000000
Current batch : 32
Batch [33/1000], Loss: 215158176.000000
Current batch : 33
Batch [34/1000], Loss: 253169856.000000
Current batch : 0
Batch [1/1000], Loss: 105951152.000000
Current batch : 1
Batch [2/1000], Loss: 253318896.000000
Current batch : 2
Batch [3/1000], Loss: 242716432.000000
Current batch : 3
Batch [4/1000], Loss: 126529728.000000
Current batch : 4
Batch [5/1000], Loss: 121479584.000000
Current batch : 5
Batch [6/1000], Loss: 160823280.000000
Current batch : 6

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([14])) that is different to the input size (torch.Size([14, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Streaming output truncated to the last 5000 lines.
Current batch : 16
Batch [17/1000], Loss: 143621152.000000
Current batch : 17
Batch [18/1000], Loss: 106052808.000000
Current batch : 18
Batch [19/1000], Loss: 142981552.000000
Current batch : 19
Batch [20/1000], Loss: 126583184.000000
Current batch : 20
Batch [21/1000], Loss: 180643872.000000
Current batch : 21
Batch [22/1000], Loss: 236261232.000000
Current batch : 22
Batch [23/1000], Loss: 137264592.000000
Current batch : 23
Batch [24/1000], Loss: 114984344.000000
Current batch : 24
Batch [25/1000], Loss: 77079536.000000
Current batch : 25
Batch [26/1000], Loss: 178113072.000000
Current batch : 26
Batch [27/1000], Loss: 112139352.000000
Current batch : 27
Batch [28/1000], Loss: 172973200.000000
Current batch : 28
Batch [29/1000], Loss: 85305448.000000
Current batch : 29
Batch [30/1000], Loss: 97706392.000000
Current batch : 30
Batch [31/1000], Loss: 140998736.000000
Current batch : 31
Batch [32/1000], Loss: 142306816.000000
Current batch : 32
Batch [33/1000], Loss: 221453632.000000
Current batch : 33
Batch [34/1000], Loss: 227026400.000000
Current batch : 0
Batch [1/1000], Loss: 205374992.000000
Current batch : 1
Batch [2/1000], Loss: 164903872.000000
Current batch : 2
Batch [3/1000], Loss: 205579376.000000
Current batch : 3
Batch [4/1000], Loss: 120461344.000000
Current batch : 4
Batch [5/1000], Loss: 118381120.000000
Current batch : 5
Batch [6/1000], Loss: 76563160.000000
Current batch : 6
Batch [7/1000], Loss: 142838208.000000
Current batch : 7
Batch [8/1000], Loss: 122289712.000000
Current batch : 8
Batch [9/1000], Loss: 165107664.000000
Current batch : 9
Batch [10/1000], Loss: 135016992.000000
Current batch : 10
Batch [11/1000], Loss: 252580848.000000
Current batch : 11
Batch [12/1000], Loss: 65476600.000000
Current batch : 12
Batch [13/1000], Loss: 195462768.000000
Current batch : 13
Batch [14/1000], Loss: 127066608.000000
Current batch : 14
Batch [15/1000], Loss: 87292800.000000
Current batch : 15
Batch [16/1000], Loss: 148905120.000000
Current batch : 16
Batch [17/1000], Loss: 96638496.000000
Current batch : 17
Batch [18/1000], Loss: 94337208.000000
Current batch : 18
Batch [19/1000], Loss: 203573680.000000
Current batch : 19
Batch [20/1000], Loss: 204711968.000000
Current batch : 20
Batch [21/1000], Loss: 128775024.000000
Current batch : 21
Batch [22/1000], Loss: 160058192.000000
Current batch : 22
Batch [23/1000], Loss: 177793408.000000
Current batch : 23
Batch [24/1000], Loss: 71547664.000000
Current batch : 24
Batch [25/1000], Loss: 99373888.000000
Current batch : 25
Batch [26/1000], Loss: 141384144.000000
Current batch : 26
Batch [27/1000], Loss: 159652448.000000
Current batch : 27
Batch [28/1000], Loss: 204363184.000000
Current batch : 28
Batch [29/1000], Loss: 192798624.000000
Current batch : 29
Batch [30/1000], Loss: 110827896.000000
Current batch : 30
Batch [31/1000], Loss: 153351072.000000
Current batch : 31
Batch [32/1000], Loss: 153367872.000000
Current batch : 32
Batch [33/1000], Loss: 149331616.000000
Current batch : 33
Batch [34/1000], Loss: 155531072.000000
Current batch : 0
Batch [1/1000], Loss: 191645712.000000
Current batch : 1
Batch [2/1000], Loss: 101646104.000000
Current batch : 2
Batch [3/1000], Loss: 115001224.000000
Current batch : 3
Batch [4/1000], Loss: 198746576.000000
Current batch : 4
Batch [5/1000], Loss: 128175696.000000
Current batch : 5
Batch [6/1000], Loss: 126523888.000000
Current batch : 6
Batch [7/1000], Loss: 107908312.000000
Current batch : 7
Batch [8/1000], Loss: 174336976.000000
Current batch : 8
Batch [9/1000], Loss: 163709984.000000
Current batch : 9
Batch [10/1000], Loss: 158595248.000000
Current batch : 10
Batch [11/1000], Loss: 190685296.000000
Current batch : 11
Batch [12/1000], Loss: 81373184.000000
Current batch : 12
Batch [13/1000], Loss: 278307616.000000
Current batch : 13
Batch [14/1000], Loss: 184006992.000000
Current batch : 14
Batch [15/1000], Loss: 115347976.000000
Current batch : 15
Batch [16/1000], Loss: 195015248.000000
Current batch : 16
Batch [17/1000], Loss: 158869360.000000
Current batch : 17
Batch [18/1000], Loss: 99404488.000000
Current batch : 18
Batch [19/1000], Loss: 112855328.000000
Current batch : 19
Batch [20/1000], Loss: 88138368.000000
Current batch : 20
Batch [21/1000], Loss: 163408432.000000
Current batch : 21
Batch [22/1000], Loss: 123179536.000000
Current batch : 22
Batch [23/1000], Loss: 186275872.000000
Current batch : 23
Batch [24/1000], Loss: 217777760.000000
Current batch : 24
Batch [25/1000], Loss: 130941848.000000
Current batch : 25
Batch [26/1000], Loss: 58280216.000000
Current batch : 26
Batch [27/1000], Loss: 162467776.000000
Current batch : 27
Batch [28/1000], Loss: 86593952.000000
Current batch : 28
Batch [29/1000], Loss: 177237056.000000
Current batch : 29
Batch [30/1000], Loss: 136828768.000000
Current batch : 30
Batch [31/1000], Loss: 140429232.000000
Current batch : 31
Batch [32/1000], Loss: 104911296.000000
Current batch : 32
Batch [33/1000], Loss: 178625248.000000
Current batch : 33
Batch [34/1000], Loss: 94163328.000000
Current batch : 0
Batch [1/1000], Loss: 131289672.000000
Current batch : 1
Batch [2/1000], Loss: 163423472.000000
Current batch : 2
Batch [3/1000], Loss: 175434992.000000
Current batch : 3
Batch [4/1000], Loss: 85431312.000000
Current batch : 4
Batch [5/1000], Loss: 164111744.000000
Current batch : 5
Batch [6/1000], Loss: 69767704.000000
Current batch : 6
Batch [7/1000], Loss: 173319376.000000
Current batch : 7
Batch [8/1000], Loss: 143481312.000000
Current batch : 8
Batch [9/1000], Loss: 113401488.000000
Current batch : 9
Batch [10/1000], Loss: 86291368.000000
Current batch : 10
Batch [11/1000], Loss: 124540944.000000
Current batch : 11
Batch [12/1000], Loss: 141843504.000000
Current batch : 12
Batch [13/1000], Loss: 69152232.000000
Current batch : 13
Batch [14/1000], Loss: 200684768.000000
Current batch : 14
Batch [15/1000], Loss: 119062928.000000
Current batch : 15
Batch [16/1000], Loss: 136512256.000000
Current batch : 16
Batch [17/1000], Loss: 170340608.000000
Current batch : 17
Batch [18/1000], Loss: 103001008.000000
Current batch : 18
Batch [19/1000], Loss: 69137560.000000
Current batch : 19
Batch [20/1000], Loss: 166959376.000000
Current batch : 20
Batch [21/1000], Loss: 144047072.000000
Current batch : 21
Batch [22/1000], Loss: 96365952.000000
Current batch : 22
Batch [23/1000], Loss: 93330728.000000
Current batch : 23
Batch [24/1000], Loss: 150552160.000000
Current batch : 24
Batch [25/1000], Loss: 105933112.000000
Current batch : 25
Batch [26/1000], Loss: 232787040.000000
Current batch : 26
Batch [27/1000], Loss: 174603072.000000
Current batch : 27
Batch [28/1000], Loss: 194111792.000000
Current batch : 28
Batch [29/1000], Loss: 188728960.000000
Current batch : 29
Batch [30/1000], Loss: 148979472.000000
Current batch : 30
Batch [31/1000], Loss: 147780768.000000
Current batch : 31
Batch [32/1000], Loss: 233286240.000000
Current batch : 32
Batch [33/1000], Loss: 165337520.000000
Current batch : 33
Batch [34/1000], Loss: 395656416.000000
Current batch : 0
Batch [1/1000], Loss: 180332192.000000
Current batch : 1
Batch [2/1000], Loss: 109704416.000000
Current batch : 2
Batch [3/1000], Loss: 222447936.000000
Current batch : 3
Batch [4/1000], Loss: 168618624.000000
Current batch : 4
Batch [5/1000], Loss: 127322008.000000
Current batch : 5
Batch [6/1000], Loss: 236021248.000000
Current batch : 6
Batch [7/1000], Loss: 140457376.000000
Current batch : 7
Batch [8/1000], Loss: 151275296.000000
Current batch : 8
Batch [9/1000], Loss: 163955312.000000
Current batch : 9
Batch [10/1000], Loss: 278703360.000000
Current batch : 10
Batch [11/1000], Loss: 125085248.000000
Current batch : 11
Batch [12/1000], Loss: 117647688.000000
Current batch : 12
Batch [13/1000], Loss: 115047296.000000
Current batch : 13
Batch [14/1000], Loss: 122591792.000000
Current batch : 14
Batch [15/1000], Loss: 209180384.000000
Current batch : 15
Batch [16/1000], Loss: 132872664.000000
Current batch : 16
Batch [17/1000], Loss: 66711672.000000
Current batch : 17
Batch [18/1000], Loss: 89767952.000000
Current batch : 18
Batch [19/1000], Loss: 131537352.000000
Current batch : 19
Batch [20/1000], Loss: 137374528.000000
Current batch : 20
Batch [21/1000], Loss: 120204384.000000
Current batch : 21
Batch [22/1000], Loss: 70924248.000000
Current batch : 22
Batch [23/1000], Loss: 142893072.000000
Current batch : 23
Batch [24/1000], Loss: 176260112.000000
Current batch : 24
Batch [25/1000], Loss: 142031744.000000
Current batch : 25
Batch [26/1000], Loss: 220167008.000000
Current batch : 26
Batch [27/1000], Loss: 127895920.000000
Current batch : 27
Batch [28/1000], Loss: 101997608.000000
Current batch : 28
Batch [29/1000], Loss: 129707992.000000
Current batch : 29
Batch [30/1000], Loss: 165513744.000000
Current batch : 30
Batch [31/1000], Loss: 211028912.000000
Current batch : 31
Batch [32/1000], Loss: 104251016.000000
Current batch : 32
Batch [33/1000], Loss: 98357456.000000
Current batch : 33
Batch [34/1000], Loss: 112192896.000000
Current batch : 0
Batch [1/1000], Loss: 213100768.000000
Current batch : 1
Batch [2/1000], Loss: 174242912.000000
Current batch : 2
Batch [3/1000], Loss: 75974456.000000
Current batch : 3
Batch [4/1000], Loss: 61056600.000000
Current batch : 4
Batch [5/1000], Loss: 140341408.000000
Current batch : 5
Batch [6/1000], Loss: 95175168.000000
Current batch : 6
Batch [7/1000], Loss: 126305576.000000
Current batch : 7
Batch [8/1000], Loss: 242986096.000000
Current batch : 8
Batch [9/1000], Loss: 95155768.000000
Current batch : 9
Batch [10/1000], Loss: 113590936.000000
Current batch : 10
Batch [11/1000], Loss: 226107616.000000
Current batch : 11
Batch [12/1000], Loss: 178928688.000000
Current batch : 12
Batch [13/1000], Loss: 131695560.000000
Current batch : 13
Batch [14/1000], Loss: 170426624.000000
Current batch : 14
Batch [15/1000], Loss: 117885872.000000
Current batch : 15
Batch [16/1000], Loss: 148124080.000000
Current batch : 16
Batch [17/1000], Loss: 144126208.000000
Current batch : 17
Batch [18/1000], Loss: 166809328.000000
Current batch : 18
Batch [19/1000], Loss: 158056752.000000
Current batch : 19
Batch [20/1000], Loss: 124640272.000000
Current batch : 20
Batch [21/1000], Loss: 108202752.000000
Current batch : 21
Batch [22/1000], Loss: 167813344.000000
Current batch : 22
Batch [23/1000], Loss: 100025456.000000
Current batch : 23
Batch [24/1000], Loss: 221586112.000000
Current batch : 24
Batch [25/1000], Loss: 194362608.000000
Current batch : 25
Batch [26/1000], Loss: 138300832.000000
Current batch : 26
Batch [27/1000], Loss: 120418424.000000
Current batch : 27
Batch [28/1000], Loss: 234526864.000000
Current batch : 28
Batch [29/1000], Loss: 201388080.000000
Current batch : 29
Batch [30/1000], Loss: 174044864.000000
Current batch : 30
Batch [31/1000], Loss: 64549628.000000
Current batch : 31
Batch [32/1000], Loss: 109088368.000000
Current batch : 32
Batch [33/1000], Loss: 97062080.000000
Current batch : 33
Batch [34/1000], Loss: 84044480.000000
Current batch : 0
Batch [1/1000], Loss: 116549504.000000
Current batch : 1
Batch [2/1000], Loss: 71599576.000000
Current batch : 2
Batch [3/1000], Loss: 190941056.000000
Current batch : 3
Batch [4/1000], Loss: 162688288.000000
Current batch : 4
Batch [5/1000], Loss: 157180416.000000
Current batch : 5
Batch [6/1000], Loss: 132021200.000000
Current batch : 6
Batch [7/1000], Loss: 108369016.000000
Current batch : 7
Batch [8/1000], Loss: 142648352.000000
Current batch : 8
Batch [9/1000], Loss: 128637776.000000
Current batch : 9
Batch [10/1000], Loss: 235735872.000000
Current batch : 10
Batch [11/1000], Loss: 319139040.000000
Current batch : 11
Batch [12/1000], Loss: 198892416.000000
Current batch : 12
Batch [13/1000], Loss: 149683120.000000
Current batch : 13
Batch [14/1000], Loss: 142825024.000000
Current batch : 14
Batch [15/1000], Loss: 205737280.000000
Current batch : 15
Batch [16/1000], Loss: 170053600.000000
Current batch : 16
Batch [17/1000], Loss: 156980032.000000
Current batch : 17
Batch [18/1000], Loss: 105402384.000000
Current batch : 18
Batch [19/1000], Loss: 129153536.000000
Current batch : 19
Batch [20/1000], Loss: 170345504.000000
Current batch : 20
Batch [21/1000], Loss: 94960936.000000
Current batch : 21
Batch [22/1000], Loss: 152756672.000000
Current batch : 22
Batch [23/1000], Loss: 104295160.000000
Current batch : 23
Batch [24/1000], Loss: 95192440.000000
Current batch : 24
Batch [25/1000], Loss: 139926368.000000
Current batch : 25
Batch [26/1000], Loss: 115258712.000000
Current batch : 26
Batch [27/1000], Loss: 154782800.000000
Current batch : 27
Batch [28/1000], Loss: 293986368.000000
Current batch : 28
Batch [29/1000], Loss: 133121352.000000
Current batch : 29
Batch [30/1000], Loss: 135191936.000000
Current batch : 30
Batch [31/1000], Loss: 159904304.000000
Current batch : 31
Batch [32/1000], Loss: 61647080.000000
Current batch : 32
Batch [33/1000], Loss: 157207024.000000
Current batch : 33
Batch [34/1000], Loss: 68274152.000000
Current batch : 0
Batch [1/1000], Loss: 89545680.000000
Current batch : 1
Batch [2/1000], Loss: 198142976.000000
Current batch : 2
Batch [3/1000], Loss: 183448224.000000
Current batch : 3
Batch [4/1000], Loss: 100867352.000000
Current batch : 4
Batch [5/1000], Loss: 137819488.000000
Current batch : 5
Batch [6/1000], Loss: 132346448.000000
Current batch : 6
Batch [7/1000], Loss: 88662848.000000
Current batch : 7
Batch [8/1000], Loss: 86892232.000000
Current batch : 8
Batch [9/1000], Loss: 209330992.000000
Current batch : 9
Batch [10/1000], Loss: 96881392.000000
Current batch : 10
Batch [11/1000], Loss: 195225280.000000
Current batch : 11
Batch [12/1000], Loss: 168237184.000000
Current batch : 12
Batch [13/1000], Loss: 62398652.000000
Current batch : 13
Batch [14/1000], Loss: 103484000.000000
Current batch : 14
Batch [15/1000], Loss: 213231392.000000
Current batch : 15
Batch [16/1000], Loss: 160209472.000000
Current batch : 16
Batch [17/1000], Loss: 205904160.000000
Current batch : 17
Batch [18/1000], Loss: 80290248.000000
Current batch : 18
Batch [19/1000], Loss: 229890800.000000
Current batch : 19
Batch [20/1000], Loss: 128763008.000000
Current batch : 20
Batch [21/1000], Loss: 60637328.000000
Current batch : 21
Batch [22/1000], Loss: 176606784.000000
Current batch : 22
Batch [23/1000], Loss: 118608416.000000
Current batch : 23
Batch [24/1000], Loss: 98022496.000000
Current batch : 24
Batch [25/1000], Loss: 200535648.000000
Current batch : 25
Batch [26/1000], Loss: 149192784.000000
Current batch : 26
Batch [27/1000], Loss: 164798272.000000
Current batch : 27
Batch [28/1000], Loss: 180666112.000000
Current batch : 28
Batch [29/1000], Loss: 250030896.000000
Current batch : 29
Batch [30/1000], Loss: 158491088.000000
Current batch : 30
Batch [31/1000], Loss: 158710912.000000
Current batch : 31
Batch [32/1000], Loss: 97846888.000000
Current batch : 32
Batch [33/1000], Loss: 112062216.000000
Current batch : 33
Batch [34/1000], Loss: 243070304.000000
Current batch : 0
Batch [1/1000], Loss: 128841184.000000
Current batch : 1
Batch [2/1000], Loss: 156771648.000000
Current batch : 2
Batch [3/1000], Loss: 111297280.000000
Current batch : 3
Batch [4/1000], Loss: 157035600.000000
Current batch : 4
Batch [5/1000], Loss: 96706992.000000
Current batch : 5
Batch [6/1000], Loss: 71699136.000000
Current batch : 6
Batch [7/1000], Loss: 176028368.000000
Current batch : 7
Batch [8/1000], Loss: 96932304.000000
Current batch : 8
Batch [9/1000], Loss: 219529824.000000
Current batch : 9
Batch [10/1000], Loss: 104332808.000000
Current batch : 10
Batch [11/1000], Loss: 128367432.000000
Current batch : 11
Batch [12/1000], Loss: 96158920.000000
Current batch : 12
Batch [13/1000], Loss: 191450992.000000
Current batch : 13
Batch [14/1000], Loss: 214103264.000000
Current batch : 14
Batch [15/1000], Loss: 147191104.000000
Current batch : 15
Batch [16/1000], Loss: 176128272.000000
Current batch : 16
Batch [17/1000], Loss: 130786096.000000
Current batch : 17
Batch [18/1000], Loss: 127494120.000000
Current batch : 18
Batch [19/1000], Loss: 144634608.000000
Current batch : 19
Batch [20/1000], Loss: 159889216.000000
Current batch : 20
Batch [21/1000], Loss: 180328080.000000
Current batch : 21
Batch [22/1000], Loss: 206758048.000000
Current batch : 22
Batch [23/1000], Loss: 102270752.000000
Current batch : 23
Batch [24/1000], Loss: 93044760.000000
Current batch : 24
Batch [25/1000], Loss: 186959056.000000
Current batch : 25
Batch [26/1000], Loss: 102044400.000000
Current batch : 26
Batch [27/1000], Loss: 178364016.000000
Current batch : 27
Batch [28/1000], Loss: 152429792.000000
Current batch : 28
Batch [29/1000], Loss: 154554016.000000
Current batch : 29
Batch [30/1000], Loss: 203610752.000000
Current batch : 30
Batch [31/1000], Loss: 56508944.000000
Current batch : 31
Batch [32/1000], Loss: 214924944.000000
Current batch : 32
Batch [33/1000], Loss: 184640032.000000
Current batch : 33
Batch [34/1000], Loss: 203554480.000000
Current batch : 0
Batch [1/1000], Loss: 95696832.000000
Current batch : 1
Batch [2/1000], Loss: 127072664.000000
Current batch : 2
Batch [3/1000], Loss: 135739376.000000
Current batch : 3
Batch [4/1000], Loss: 198493136.000000
Current batch : 4
Batch [5/1000], Loss: 163832672.000000
Current batch : 5
Batch [6/1000], Loss: 169035808.000000
Current batch : 6
Batch [7/1000], Loss: 93238320.000000
Current batch : 7
Batch [8/1000], Loss: 112890096.000000
Current batch : 8
Batch [9/1000], Loss: 167859296.000000
Current batch : 9
Batch [10/1000], Loss: 210485072.000000
Current batch : 10
Batch [11/1000], Loss: 127717088.000000
Current batch : 11
Batch [12/1000], Loss: 160926016.000000
Current batch : 12
Batch [13/1000], Loss: 120773440.000000
Current batch : 13
Batch [14/1000], Loss: 155775552.000000
Current batch : 14
Batch [15/1000], Loss: 171971776.000000
Current batch : 15
Batch [16/1000], Loss: 171743664.000000
Current batch : 16
Batch [17/1000], Loss: 72382152.000000
Current batch : 17
Batch [18/1000], Loss: 135355200.000000
Current batch : 18
Batch [19/1000], Loss: 124573424.000000
Current batch : 19
Batch [20/1000], Loss: 116537952.000000
Current batch : 20
Batch [21/1000], Loss: 129279296.000000
Current batch : 21
Batch [22/1000], Loss: 137742128.000000
Current batch : 22
Batch [23/1000], Loss: 185194400.000000
Current batch : 23
Batch [24/1000], Loss: 190832224.000000
Current batch : 24
Batch [25/1000], Loss: 162889760.000000
Current batch : 25
Batch [26/1000], Loss: 81547200.000000
Current batch : 26
Batch [27/1000], Loss: 201095504.000000
Current batch : 27
Batch [28/1000], Loss: 189250400.000000
Current batch : 28
Batch [29/1000], Loss: 81266712.000000
Current batch : 29
Batch [30/1000], Loss: 165427744.000000
Current batch : 30
Batch [31/1000], Loss: 110127232.000000
Current batch : 31
Batch [32/1000], Loss: 152278336.000000
Current batch : 32
Batch [33/1000], Loss: 198913536.000000
Current batch : 33
Batch [34/1000], Loss: 110896264.000000
Current batch : 0
Batch [1/1000], Loss: 257561424.000000
Current batch : 1
Batch [2/1000], Loss: 167217696.000000
Current batch : 2
Batch [3/1000], Loss: 179585632.000000
Current batch : 3
Batch [4/1000], Loss: 103043456.000000
Current batch : 4
Batch [5/1000], Loss: 120500480.000000
Current batch : 5
Batch [6/1000], Loss: 123165472.000000
Current batch : 6
Batch [7/1000], Loss: 195526672.000000
Current batch : 7
Batch [8/1000], Loss: 143131968.000000
Current batch : 8
Batch [9/1000], Loss: 119520560.000000
Current batch : 9
Batch [10/1000], Loss: 165774016.000000
Current batch : 10
Batch [11/1000], Loss: 130798616.000000
Current batch : 11
Batch [12/1000], Loss: 84724488.000000
Current batch : 12
Batch [13/1000], Loss: 212929904.000000
Current batch : 13
Batch [14/1000], Loss: 267976752.000000
Current batch : 14
Batch [15/1000], Loss: 205182608.000000
Current batch : 15
Batch [16/1000], Loss: 121288672.000000
Current batch : 16
Batch [17/1000], Loss: 187766128.000000
Current batch : 17
Batch [18/1000], Loss: 102933424.000000
Current batch : 18